node {
    
    stage('Git CheckOut') {
      git branch: 'demo-code', url: 'https://github.com/amitvashisttech/devops-jenkins-acc-04May2020.git'
    }
    
    stage('Maven Clean') {
    sh label: '', script: 'mvn clean -f 02-Jenkins/petclinic-code/pom.xml'
    }
    
    stage('Maven Compile') {
    sh label: '', script: 'mvn compile -f 02-Jenkins/petclinic-code/pom.xml'
    }
    
     stage('Maven Test') {
    sh label: '', script: 'mvn test -f 02-Jenkins/petclinic-code/pom.xml'
     }
    
     stage('Maven Package') {
    sh label: '', script: 'mvn package -f 02-Jenkins/petclinic-code/pom.xml'
     }
     
    stage('Archive Artifacts') { 
    archiveArtifacts '02-Jenkins/petclinic-code/target/*.war'
    }
}
