node {
    
    stage('Git CheckOut') {
      git branch: 'demo-code', url: 'https://github.com/amitvashisttech/devops-jenkins-acc-04May2020.git'
    }
    
    def project_path = "02-Jenkins/petclinic-code"
    
    dir(project_path) {
    stage('Maven Clean') {
    sh label: '', script: 'mvn clean'
    }
    
    stage('Maven Verify') {
    sh label: '', script: 'mvn verify'
     }
     
    stage('Code Coverage') {
     publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: false, reportDir: 'target/site/jacoco/', reportFiles: 'index.html', reportName: 'Code Coverage Report', reportTitles: ''])
    }
    
    stage('Publish Test') {
    junit allowEmptyResults: true, testResults: 'target/surefire-reports/TEST-*.xml'
    }

    } 

    stage('Archive Artifacts') { 
    archiveArtifacts '02-Jenkins/petclinic-code/target/*.war'
    }
    
    
}
