---
# tasks file for tomcat
- name: Create Tomcat Home Dir. 
  file: path={{doc_tomcat}} state=directory

- name: Download Tomcat TarBall. 
  get_url: url="http://apachemirror.wuchna.com/tomcat/tomcat-8/v8.5.54/bin/apache-tomcat-8.5.54.tar.gz"  dest={{doc_tomcat}}/tomcat.tar.gz mode=0755

- name: Extact Tomcat TarBall.
  command: "tar zxf {{doc_tomcat}}/tomcat.tar.gz  -C {{doc_tomcat}} --strip-components 1"

- name: Install Java 1.8 JDK
  apt: name=default-jdk state=present

- name: Create Tomcat MyApp Dir. 
  file: path={{doc_tomcat}}/webapps/myapp state=directory

- name: Deploy Info Template Web Page
  template: src=templates/info.j2 dest={{doc_tomcat}}/webapps/myapp/info.html
  notify:
  - Restart Tomcat 

- name: Deploy Petclinic War File
  copy: src=files/petclinic.war dest={{doc_tomcat}}/webapps/ mode=0644
